# Generated by Django 4.2 on 2024-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMunicipio', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
                ('CodigoMunicipio', models.CharField(max_length=100, verbose_name='Codigo del Municipio')),
                ('Departamento', models.CharField(max_length=100, verbose_name='Departamento')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
    ]
