# Generated by Django 4.2 on 2024-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroFactura', models.IntegerField(max_length=60, verbose_name='NumeroFactura')),
                ('Precio', models.IntegerField(max_length=60, verbose_name='Precio')),
                ('Subtotal', models.IntegerField(max_length=60, verbose_name='Subtotal')),
                ('Propina', models.IntegerField(max_length=60, verbose_name='Propina')),
                ('MetodoPago', models.CharField(max_length=60, verbose_name='MetodoPago')),
                ('Descuento', models.IntegerField(max_length=60, verbose_name='Descuento')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
