# Generated by Django 4.2 on 2024-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarjeta', models.CharField(max_length=100, verbose_name='Tarjeta')),
                ('Transferencia', models.CharField(max_length=100, verbose_name='Transferencia')),
                ('Efectivo', models.CharField(max_length=100, verbose_name='Efectivo')),
            ],
            options={
                'verbose_name_plural': 'MetodoPago',
            },
        ),
    ]
