# Generated by Django 4.2 on 2024-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_platillo', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Platillo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
            ],
            options={
                'verbose_name_plural': 'Menús',
            },
        ),
    ]
