# Generated by Django 5.0.9 on 2024-11-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetalleMesa', models.CharField(max_length=6, verbose_name='DetalleMesa')),
            ],
            options={
                'verbose_name': 'Ordenes',
            },
        ),
    ]
