# Generated by Django 4.2 on 2024-09-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroFactura', models.CharField(max_length=50, verbose_name='NumeroFactura')),
                ('NumeroMesa', models.CharField(max_length=50, verbose_name='NumeroMesa')),
                ('MetodoPago', models.CharField(max_length=60, verbose_name='MetodoPago')),
                ('Descuento', models.CharField(max_length=50, verbose_name='Descuento')),
                ('Propina', models.CharField(max_length=50, verbose_name='Propina')),
                ('Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factura.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name_plural': 'DetalleFactura',
            },
        ),
    ]
