# Generated by Django 4.2 on 2024-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroMesas', models.CharField(max_length=100, verbose_name='NumeroMesas')),
                ('CapacidadMesas', models.CharField(max_length=60, verbose_name='CapacidadMesas')),
            ],
            options={
                'verbose_name_plural': 'Mesa',
            },
        ),
    ]
