# Generated by Django 4.2 on 2024-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePlatillo', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Platillo')),
                ('Descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('Precio', models.IntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
